# Copyright © 2019 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Example JSON segments and filings that are known to work.

These can be used in other tests as basis for the JSON filings.
"""
from .affiliated_businesses import AFFILIATED_BUSINESSES
from .business_documents import COGS, CSTAT, LSEAL, SUMMARY
from .schema_data import (
    ADDRESS,
    ADMIN_FREEZE,
    AGM_EXTENSION,
    AGM_LOCATION_CHANGE,
    ALL_FILINGS,
    ALTERATION,
    ALTERATION_FILING_TEMPLATE,
    AMALGAMATION_APPLICATION,
    AMALGAMATION_OUT,
    ANNUAL_REPORT,
    BEN_CONVERSION,
    BUSINESS,
    BUSINESS_HISTORICAL,
    CHANGE_OF_ADDRESS,
    CHANGE_OF_DIRECTORS,
    CHANGE_OF_DIRECTORS_MAILING,
    CHANGE_OF_LIQUIDATORS,
    CHANGE_OF_NAME,
    CHANGE_OF_OFFICERS,
    CHANGE_OF_RECEIVERS,
    CHANGE_OF_REGISTRATION,
    CHANGE_OF_REGISTRATION_TEMPLATE,
    COMMENT_BUSINESS,
    COMMENT_FILING,
    CONSENT_AMALGAMATION_OUT,
    CONSENT_CONTINUATION_OUT,
    CONTINUATION_IN,
    CONTINUATION_IN_FILING_TEMPLATE,
    CONTINUATION_OUT,
    CONVERSION_FILING_TEMPLATE,
    COOPERATIVE,
    CORP_CHANGE_OF_ADDRESS,
    CORRECTION_AR,
    CORRECTION_CHANGE_OF_REGISTRATION,
    CORRECTION_COA,
    CORRECTION_COD,
    CORRECTION_COMBINED_AR,
    CORRECTION_CONVERSION,
    CORRECTION_CP_SPECIAL_RESOLUTION,
    CORRECTION_INCORPORATION,
    CORRECTION_REGISTRATION,
    COURT_ORDER,
    COURT_ORDER_FILING_TEMPLATE,
    CP_SPECIAL_RESOLUTION_TEMPLATE,
    DELAY_DISSOLUTION,
    DISSOLUTION,
    FILING_HEADER,
    FILING_TEMPLATE,
    FILINGS_WITH_TYPES,
    FIRMS_CONVERSION,
    INCORPORATION,
    INCORPORATION_FILING_TEMPLATE,
    NOTICE_OF_WITHDRAWAL,
    PUT_BACK_OFF,
    PUT_BACK_ON,
    REGISTRARS_NOTATION,
    REGISTRARS_NOTATION_FILING_TEMPLATE,
    REGISTRARS_ORDER,
    REGISTRARS_ORDER_FILING_TEMPLATE,
    REGISTRATION,
    RESTORATION,
    SPECIAL_RESOLUTION,
    STUB_FILING,
    TRANSITION,
    TRANSITION_FILING_TEMPLATE,
    TRANSPARENCY_REGISTER,
    UNMANAGED,
)
