/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TheCacheIdOfTheMostCurrentLedgerRecord = number;
export type TheTimestampOfTheMostCurrentLedgerRecord = string;
export type TheTimestampOfTheLastLedgerRecordBeforeDataLoadFromCobrsByBob = string;
export type TheDissolutionDateSchema = string;
export type TheFiscalYearEndDateSchema = string;
export type TheFoundingDateSchema = string;
export type TheIdentifierSchema = string;
export type TheLegalNameSchema = string;
export type TheLegalTypeOfTheBusiness =
  | "A"
  | "B"
  | "BC"
  | "BEN"
  | "C"
  | "CC"
  | "CCC"
  | "CEM"
  | "CP"
  | "CS"
  | "CUL"
  | "EPR"
  | "FI"
  | "FOR"
  | "GP"
  | "LIC"
  | "LIB"
  | "LL"
  | "LLC"
  | "LP"
  | "MF"
  | "PA"
  | "PAR"
  | "PFS"
  | "QA"
  | "QB"
  | "QC"
  | "QD"
  | "QE"
  | "REG"
  | "RLY"
  | "S"
  | "SB"
  | "SP"
  | "T"
  | "TMY"
  | "ULC"
  | "UQA"
  | "UQB"
  | "UQC"
  | "UQD"
  | "UQE"
  | "XCP"
  | "XL"
  | "XP"
  | "XS";
export type TheTaxIdSchema = string;
export type TheStateOfTheBusiness = "ACTIVE" | "HISTORICAL" | "LIQUIDATION";
export type TheLinkToTheFilingThatChangedTheBusinessStateIfApplicableS = string;
export type IndicatesWhetherTheBusinessIsInGoodStanding = boolean;
export type IndicatesWhetherTheBusinessIsInAdministrativeFreeze = boolean;
export type WarningCode = string;
export type WarningMessage = string;
export type WarningType = string;
export type TheLinkToTheFilingThatResultedInTheNonCompliance = string;

export interface TheBusinessesSchema {
  business: TheBusinessSchema;
  [k: string]: unknown;
}
export interface TheBusinessSchema {
  cacheId?: TheCacheIdOfTheMostCurrentLedgerRecord;
  lastLedgerTimestamp?: TheTimestampOfTheMostCurrentLedgerRecord;
  lastPreBobFilingTimestamp?: TheTimestampOfTheLastLedgerRecordBeforeDataLoadFromCobrsByBob;
  dissolutionDate?: TheDissolutionDateSchema;
  fiscalYearEndDate?: TheFiscalYearEndDateSchema;
  foundingDate?: TheFoundingDateSchema;
  identifier: TheIdentifierSchema;
  legalName?: TheLegalNameSchema;
  legalType?: TheLegalTypeOfTheBusiness;
  taxId?: TheTaxIdSchema;
  state?: TheStateOfTheBusiness;
  stateFiling?: TheLinkToTheFilingThatChangedTheBusinessStateIfApplicableS;
  goodStanding?: IndicatesWhetherTheBusinessIsInGoodStanding;
  adminFreeze?: IndicatesWhetherTheBusinessIsInAdministrativeFreeze;
  warnings?: Warning[];
  naics?: NAICS;
  /**
   * A brief note to explain the nature of business.
   */
  natureOfBusiness?: string;
  [k: string]: unknown;
}
export interface Warning {
  code?: WarningCode;
  message?: WarningMessage;
  warningType?: WarningType;
  filing?: TheLinkToTheFilingThatResultedInTheNonCompliance;
  [k: string]: unknown;
}
export interface NAICS {
  naicsCode?: string;
  naicsDescription?: string;
  [k: string]: unknown;
}
