/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TheAssociationTypeForCooperativeFiling = "CP" | "HC" | "CSC";
export type TheIdentifierForRulesFileInFileServer = string;
export type TheFileNameWhileUploading = string;
export type TheIdentifierForMemorandumFileInFileServer = string;
export type TheFileNameWhileUploading1 = string;

export interface CooperativeSchema {
  cooperativeAssociationType: TheAssociationTypeForCooperativeFiling;
  rulesFileKey: TheIdentifierForRulesFileInFileServer;
  rulesFileName: TheFileNameWhileUploading;
  memorandumFileKey: TheIdentifierForMemorandumFileInFileServer;
  memorandumFileName: TheFileNameWhileUploading1;
  [k: string]: unknown;
}
