/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PreviousFirstNameInTheCaseOfALegalNameChangeInAFiling = string;
export type PreviousLastNameInTheCaseOfALegalNameChangeInAFiling = string;
export type PreviousMiddleNameInTheCaseOfALegalNameChangeInAFiling = string;

export interface TheDirectorsSchema {
  directors: Director[];
  [k: string]: unknown;
}
export interface Director {
  officer: Person;
  deliveryAddress: TheAddressSchema;
  mailingAddress?: TheAddressSchema;
  title?: string;
  appointmentDate: string;
  cessationDate: string | null;
  [k: string]: unknown;
}
export interface Person {
  firstName: string;
  lastName: string;
  middleInitial?: string;
  prevFirstName?: PreviousFirstNameInTheCaseOfALegalNameChangeInAFiling;
  prevLastName?: PreviousLastNameInTheCaseOfALegalNameChangeInAFiling;
  prevMiddleInitial?: PreviousMiddleNameInTheCaseOfALegalNameChangeInAFiling;
  [k: string]: unknown;
}
export interface TheAddressSchema {
  streetAddress: string;
  streetAddressAdditional?: string;
  addressCity: string;
  addressCountry: string;
  addressRegion: string | null;
  postalCode: string;
  deliveryInstructions?: string | null;
  [k: string]: unknown;
}
