/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TheTypeOfDissolutionSuchAsAdministrativeVoluntaryEtc =
  | "administrative"
  | "involuntary"
  | "voluntary"
  | "voluntaryLiquidation"
  | "courtOrderedLiquidation";
export type TheDissolvedCompanyHasOutstandingLiabilities = boolean;
export type Person = (
  | {
      partyType?: "person";
      [k: string]: unknown;
    }
  | {
      partyType?: "organization";
      [k: string]: unknown;
    }
) & {
  partyType: TheTypeOfParty;
  firstName?: string;
  lastName?: string;
  middleInitial?: string;
  organizationName?: string;
  identifier?: TheIdentifierIncorporationNumberIfAvailableForOrganization;
  taxId?: TheCRABusinessNumber;
  email?: string;
  [k: string]: unknown;
};
export type TheTypeOfParty = "organization" | "person";
export type TheIdentifierIncorporationNumberIfAvailableForOrganization = string;
export type TheCRABusinessNumber = string;
export type TheIdentifierForAffidavitFileInFileServer = string;
export type TheFileNameWhileUploading = string;

export interface Dissolution {
  dissolution: {
    dissolutionDate: string;
    dissolutionType: TheTypeOfDissolutionSuchAsAdministrativeVoluntaryEtc;
    details?: string;
    dissolutionStatementType?: string;
    hasLiabilities?: TheDissolvedCompanyHasOutstandingLiabilities;
    parties?: Party[];
    courtOrder?: CourtOrder;
    custodialOffice?: TheOfficeSchema;
    affidavitFileKey?: TheIdentifierForAffidavitFileInFileServer;
    affidavitFileName?: TheFileNameWhileUploading;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Party {
  officer: Person;
  deliveryAddress?: TheAddressSchema;
  mailingAddress: TheAddressSchema;
  title?: string;
  roles: PartyRole[];
  [k: string]: unknown;
}
export interface TheAddressSchema {
  streetAddress: string;
  streetAddressAdditional?: string;
  addressCity: string;
  addressCountry: string;
  addressRegion: string | null;
  postalCode: string;
  deliveryInstructions?: string | null;
  [k: string]: unknown;
}
export interface PartyRole {
  roleType: "Completing Party" | "Custodian" | "Liquidator" | "Director" | "Incorporator" | "Proprietor" | "Partner";
  appointmentDate: string;
  cessationDate?: string | null;
  [k: string]: unknown;
}
export interface CourtOrder {
  /**
   * The court assigns each court order a unique file number up to 20 characters in length.
   */
  fileNumber: string;
  /**
   * The date and time of the court order.
   */
  orderDate?: string;
  /**
   * planOfArrangement
   */
  effectOfOrder?: string;
  /**
   * A brief note to explain the purpose of the Court Order.
   */
  orderDetails?: string;
  [k: string]: unknown;
}
export interface TheOfficeSchema {
  officeType?: string;
  mailingAddress: TheAddressSchema;
  deliveryAddress: TheAddressSchema;
  [k: string]: unknown;
}
