/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TheOfficeSchema {
  officeType?: string;
  mailingAddress: TheAddressSchema;
  deliveryAddress: TheAddressSchema;
  [k: string]: unknown;
}
export interface TheAddressSchema {
  streetAddress: string;
  streetAddressAdditional?: string;
  addressCity: string;
  addressCountry: string;
  addressRegion: string | null;
  postalCode: string;
  deliveryInstructions?: string | null;
  [k: string]: unknown;
}
