/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Person = Person1 & {
  partyType: TheTypeOfParty;
  firstName?: string;
  lastName?: string;
  middleInitial?: string;
  organizationName?: string;
  identifier?: TheIdentifierIncorporationNumberIfAvailableForOrganization;
  taxId?: TheCRABusinessNumber;
  email?: string;
  [k: string]: unknown;
};
export type Person1 =
  | {
      partyType?: "person";
      [k: string]: unknown;
    }
  | {
      partyType?: "organization";
      [k: string]: unknown;
    };
export type TheTypeOfParty = "organization" | "person";
export type TheIdentifierIncorporationNumberIfAvailableForOrganization = string;
export type TheCRABusinessNumber = string;

export interface TheCorpPartiesSchema {
  parties: Party[];
  [k: string]: unknown;
}
export interface Party {
  officer: Person;
  deliveryAddress?: TheAddressSchema;
  mailingAddress: TheAddressSchema;
  title?: string;
  roles: PartyRole[];
  [k: string]: unknown;
}
export interface TheAddressSchema {
  streetAddress: string;
  streetAddressAdditional?: string;
  addressCity: string;
  addressCountry: string;
  addressRegion: string | null;
  postalCode: string;
  deliveryInstructions?: string | null;
  [k: string]: unknown;
}
export interface PartyRole {
  roleType: "Completing Party" | "Custodian" | "Liquidator" | "Director" | "Incorporator" | "Proprietor" | "Partner";
  appointmentDate: string;
  cessationDate?: string | null;
  [k: string]: unknown;
}
