/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TheNameOfTheShareClass = string;
export type TheDisplayOrderOfTheSharesThatIndicatesPriority = number;
export type MaximumNumberOfSharesInTheClass = number | null;
export type InitialValueOfEachShare = number | null;
export type HasMaximumNumberOfShares = boolean;
export type HasInitialValueOfEachShare = boolean;
export type HasSpecialRightsOrRestrictions = boolean;
export type TheNameOfTheShareSeries = string;
export type TheDisplayOrderThatIndicatesPriority = number;
export type MaximumNumberOfSharesInTheSeries = number | null;
export type HasMaximumNumberOfShares1 = boolean;
export type HasSpecialRightsOrRestrictions1 = boolean;

export interface ShareStructureSchema {
  resolutionDates?: string[];
  shareClasses: ShareClass[];
  [k: string]: unknown;
}
export interface ShareClass {
  name: TheNameOfTheShareClass;
  priority: TheDisplayOrderOfTheSharesThatIndicatesPriority;
  maxNumberOfShares: MaximumNumberOfSharesInTheClass;
  parValue: InitialValueOfEachShare;
  currency: string | null;
  hasMaximumShares: HasMaximumNumberOfShares;
  hasParValue: HasInitialValueOfEachShare;
  hasRightsOrRestrictions: HasSpecialRightsOrRestrictions;
  series?: ShareSeries[];
  [k: string]: unknown;
}
export interface ShareSeries {
  name: TheNameOfTheShareSeries;
  priority: TheDisplayOrderThatIndicatesPriority;
  maxNumberOfShares: MaximumNumberOfSharesInTheSeries;
  hasMaximumShares: HasMaximumNumberOfShares1;
  hasRightsOrRestrictions: HasSpecialRightsOrRestrictions1;
  [k: string]: unknown;
}
