/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AnAdditionalNameForAPersonCanBeUsedForAMiddleName = string;

export interface SpecialResolution {
  specialResolution: {
    meetingDate?: string;
    resolution: string;
    resolutionDate?: string;
    signingDate?: string;
    signatory?: PersonSchema;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface PersonSchema {
  givenName?: string;
  familyName?: string;
  additionalName?: AnAdditionalNameForAPersonCanBeUsedForAMiddleName;
  middleInitial?: string;
  email?: string;
  [k: string]: unknown;
}
